removed task2 convolution, added task5 3D origin and shifted tasks in…
kapecp/ppgso pull request #3
Opened 2019-09-19 07:23 UTC by martinmadaras

… between

2019-09-22 11:40 UTC, kapecp requested changes

2019-09-22 11:40 UTC, kapecp commented on src/task5_3d_origin/task5_3d_origin.cpp
> +using namespace std;
`using namespace` treba odstranit

2019-09-22 11:40 UTC, kapecp commented on src/task2_bresenham/task2_bresenham.cpp
> +  image::saveBMP(framebuffer, "task2_bresenham.bmp");
odporucam pridat namespace `ppgso::` a `std::`

2019-09-23 06:19 UTC, martinmadaras commented
ok, spravil som tak

On Sun, Sep 22, 2019 at 1:40 PM Peter Kapec <notifications@github.com>
wrote:

> *@kapecp* requested changes on this pull request.
> ------------------------------
>
> In src/task5_3d_origin/task5_3d_origin.cpp
> <https://github.com/kapecp/ppgso/pull/3#discussion_r326896283>:
>
> > +//        - Use color_vert/frag shader to display the polygon
> +//        - Animate the rotation of the all 3 axis and the cube.
> +
> +#include <iostream>
> +#include <vector>
> +
> +#define GLM_ENABLE_EXPERIMENTAL
> +#include <glm/glm.hpp>
> +#include <glm/gtx/matrix_transform_2d.hpp>
> +#include <glm/gtx/euler_angles.hpp>
> +#include <ppgso/ppgso.h>
> +
> +#include <shaders/color_vert_glsl.h>
> +#include <shaders/color_frag_glsl.h>
> +
> +using namespace std;
>
> using namespace treba odstranit
> ------------------------------
>
> In src/task2_bresenham/task2_bresenham.cpp
> <https://github.com/kapecp/ppgso/pull/3#discussion_r326896339>:
>
> > @@ -33,8 +33,8 @@ int main()
>      drawLine(framebuffer, points[i], points[i+1]);
>
>    // Save the result
> -  std::cout << "Generating task3_bresenham.bmp file ..." << std::endl;
> -  ppgso::image::saveBMP(framebuffer, "task3_bresenham.bmp");
> +  cout << "Generating task2_bresenham.bmp file ..." << endl;
> +  image::saveBMP(framebuffer, "task2_bresenham.bmp");
>
> odporucam pridat namespace ppgso:: a std::
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/kapecp/ppgso/pull/3?email_source=notifications&email_token=ABN27Z54QEGQH4TNO5FHCSLQK5KSBA5CNFSM4IYHNK22YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFP7X5A#pullrequestreview-291503092>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABN27Z2RK6SSXMSYRR26YBTQK5KSBANCNFSM4IYHNK2Q>
> .
>

2019-09-24 15:08 UTC, merged